// 1000 pre-written debate motions used to rotate the placeholder text on
// the battle topic input (see useRotatingPlaceholder in app/battle/[id]/page.tsx).
// Order here doesn't matter — the hook shuffles at mount time.
export const DEBATE_TOPICS: string[] = [
  "Do you support the plan to abolish credit scores as a hiring criterion?",
  "Do you support the plan to abolish daylight billboard advertising in cities?",
  "Do you support the plan to abolish daylight saving time?",
  "Do you support the plan to abolish exclusivity deals between streaming platforms and studios?",
  "Do you support the plan to abolish for-profit prisons?",
  "Do you support the plan to abolish grades in favor of narrative feedback?",
  "Do you support the plan to abolish homework in schools?",
  "Do you support the plan to abolish legacy admissions at universities?",
  "Do you support the plan to abolish mandatory overtime in hospitals?",
  "Do you support the plan to abolish mandatory retirement ages?",
  "Do you support the plan to abolish minimum order fees for food delivery?",
  "Do you support the plan to abolish non-compete clauses in employment contracts?",
  "Do you support the plan to abolish standardized dress codes at work?",
  "Do you support the plan to abolish standardized school uniforms?",
  "Do you support the plan to abolish standardized university entrance exams?",
  "Do you support the plan to abolish the death penalty worldwide?",
  "Do you support the plan to abolish the electoral college?",
  "Do you support the plan to abolish the penny and round all cash transactions?",
  "Do you support the plan to abolish tipping and build service costs into prices?",
  "Do you support the plan to abolish unpaid overtime?",
  "Do you support the plan to abolish unpaid student teaching placements?",
  "Do you support the plan to ban advertising during children's television?",
  "Do you support the plan to ban autonomous weapons in warfare?",
  "Do you support the plan to ban breed-specific legislation for dogs?",
  "Do you support the plan to ban cosmetic testing on animals worldwide?",
  "Do you support the plan to ban drive-through lanes at new restaurants?",
  "Do you support the plan to ban excessive packaging on online orders?",
  "Do you support the plan to ban facial recognition in public spaces?",
  "Do you support the plan to ban fast fashion advertising?",
  "Do you support the plan to ban gas-powered cars in city centers?",
  "Do you support the plan to ban late fees on public library books?",
  "Do you support the plan to ban leaf blowers and other small gas engines?",
  "Do you support the plan to ban leaf litter burning in residential areas?",
  "Do you support the plan to ban lobbying by corporations?",
  "Do you support the plan to ban microplastic-shedding synthetic fabrics?",
  "Do you support the plan to ban misleading 'natural' labels on food?",
  "Do you support the plan to ban planned obsolescence in consumer electronics?",
  "Do you support the plan to ban plastic microbeads in cosmetics?",
  "Do you support the plan to ban plastic packaging for produce?",
  "Do you support the plan to ban plastic straws and cutlery in restaurants?",
  "Do you support the plan to ban predatory payday lending?",
  "Do you support the plan to ban predictive policing algorithms?",
  "Do you support the plan to ban private ownership of handguns?",
  "Do you support the plan to ban single-use coffee pods?",
  "Do you support the plan to ban single-use plastic bags in grocery stores?",
  "Do you support the plan to ban single-use plastics nationwide?",
  "Do you support the plan to ban social media for under-16s?",
  "Do you support the plan to ban surge pricing during emergencies?",
  "Do you support the plan to ban surge pricing on essential medicines?",
  "Do you support the plan to ban targeted advertising to children?",
  "Do you support the plan to ban targeted political ads on social media?",
  "Do you support the plan to ban the sale of energy drinks to minors?",
  "Do you support the plan to ban the sale of exotic animals as pets?",
  "Do you support the plan to ban the use of child actors in advertising?",
  "Do you support the plan to ban unpaid internships?",
  "Do you support the plan to ban unsolicited robocalls entirely?",
  "Do you support the plan to ban zoos and aquariums?",
  "Do you support the plan to cap CEO pay at a fixed multiple of the lowest-paid worker?",
  "Do you support the plan to give animals basic legal rights?",
  "Do you support the plan to give citizens a legal right to be forgotten online?",
  "Do you support the plan to give citizens a legal right to paid sick leave?",
  "Do you support the plan to give citizens a right to a paper ballot as backup?",
  "Do you support the plan to give citizens a right to repair their own devices?",
  "Do you support the plan to give citizens a right to request a human customer service agent?",
  "Do you support the plan to give citizens a say in how police budgets are spent?",
  "Do you support the plan to give citizens free annual health checkups?",
  "Do you support the plan to give citizens free legal aid for housing disputes?",
  "Do you support the plan to give citizens paid time off to vote?",
  "Do you support the plan to give citizens the right to a four-day school week?",
  "Do you support the plan to give citizens the right to disconnect after work hours?",
  "Do you support the plan to give citizens the right to vote at sixteen?",
  "Do you support the plan to give employees a seat on every corporate board?",
  "Do you support the plan to give every citizen a universal basic income?",
  "Do you support the plan to give every citizen thirty days of paid leave a year?",
  "Do you support the plan to give every new parent a state-funded newborn care package?",
  "Do you support the plan to give every student access to free school meals?",
  "Do you support the plan to give every worker the right to a four-day trial workweek?",
  "Do you support the plan to give farmers direct subsidies instead of market price supports?",
  "Do you support the plan to give renters a legal cap on annual rent increases?",
  "Do you support the plan to give renters the right to buy the home they rent?",
  "Do you support the plan to give small businesses priority in public procurement?",
  "Do you support the plan to give small farms priority access to public land?",
  "Do you support the plan to give whistleblowers guaranteed legal protection?",
  "Do you support the plan to grant legal personhood to advanced AI systems?",
  "Do you support the plan to legalize all recreational drugs?",
  "Do you support the plan to make climate education mandatory in schools?",
  "Do you support the plan to make college tuition free at public universities?",
  "Do you support the plan to make companies responsible for recycling their own products?",
  "Do you support the plan to make composting mandatory in cities?",
  "Do you support the plan to make every new appliance carry an energy-use label?",
  "Do you support the plan to make financial literacy a required school subject?",
  "Do you support the plan to make four-day work weeks the legal standard?",
  "Do you support the plan to make internet access a basic human right?",
  "Do you support the plan to make it a legal right to work remotely where the job allows it?",
  "Do you support the plan to make it illegal to advertise diet products to teenagers?",
  "Do you support the plan to make it illegal to fire someone without cause?",
  "Do you support the plan to make it illegal to make employees check email after hours?",
  "Do you support the plan to make it illegal to patent naturally occurring genes?",
  "Do you support the plan to make it illegal to sell personal data without consent?",
  "Do you support the plan to make it mandatory for airlines to compensate for long delays?",
  "Do you support the plan to make it mandatory for hospitals to publish wait times?",
  "Do you support the plan to make it mandatory for landlords to allow pets?",
  "Do you support the plan to make it mandatory for schools to teach financial planning?",
  "Do you support the plan to make it mandatory to label lab-grown meat clearly?",
  "Do you support the plan to make it mandatory to learn CPR in high school?",
  "Do you support the plan to make it mandatory to recycle electronics at point of sale?",
  "Do you support the plan to make jury duty compensated at a living wage?",
  "Do you support the plan to make menstrual products free in public restrooms?",
  "Do you support the plan to make organ donation opt-out by default?",
  "Do you support the plan to make patents on life-saving drugs expire faster?",
  "Do you support the plan to make public bathrooms free everywhere?",
  "Do you support the plan to make public defenders as well-funded as prosecutors?",
  "Do you support the plan to make public libraries offer free internet and device loans?",
  "Do you support the plan to make public parks off-limits to pesticide use?",
  "Do you support the plan to make public transit fare based on income?",
  "Do you support the plan to make public transport free for everyone?",
  "Do you support the plan to make recycling contamination fines apply to households?",
  "Do you support the plan to make space exploration a shared global effort rather than a national one?",
  "Do you support the plan to make term limits mandatory for legislators?",
  "Do you support the plan to make traffic fines proportional to income?",
  "Do you support the plan to make voter registration automatic at eighteen?",
  "Do you support the plan to make voting mandatory for all adults?",
  "Do you support the plan to make voting possible entirely online?",
  "Do you support the plan to replace prisons with rehabilitation-focused centers?",
  "Do you support the plan to replace standardized testing with project-based assessment?",
  "Do you support the plan to require a license to have children?",
  "Do you support the plan to require all new buildings to be carbon neutral?",
  "Do you support the plan to require all packaging to be compostable within five years?",
  "Do you support the plan to require all schools to teach a second language from age five?",
  "Do you support the plan to require banks to offer free basic accounts?",
  "Do you support the plan to require companies to disclose their carbon footprint?",
  "Do you support the plan to require companies to fund the retraining of laid-off workers?",
  "Do you support the plan to require companies to give workers equity instead of bonuses?",
  "Do you support the plan to require companies to offer a living wage internship?",
  "Do you support the plan to require companies to offer opt-out of algorithmic feeds?",
  "Do you support the plan to require companies to publish supply chain audits?",
  "Do you support the plan to require companies to publish their gender pay gap?",
  "Do you support the plan to require companies to reveal what data they collect on users?",
  "Do you support the plan to require companies to take back their own packaging?",
  "Do you support the plan to require companies to test AI systems for bias before release?",
  "Do you support the plan to require ethics training for every engineer?",
  "Do you support the plan to require every apartment building to have a compost bin?",
  "Do you support the plan to require every citizen to vote or pay a fine?",
  "Do you support the plan to require every city bus to be wheelchair accessible?",
  "Do you support the plan to require every city to have a minimum share of green space?",
  "Do you support the plan to require every new car sold to be electric within a decade?",
  "Do you support the plan to require every new home to include solar panels?",
  "Do you support the plan to require every new mall to include public seating and shade?",
  "Do you support the plan to require every new phone to have a replaceable battery?",
  "Do you support the plan to require every school to grow its own vegetable garden?",
  "Do you support the plan to require every school to have a mental health counselor on site?",
  "Do you support the plan to require every workplace to offer mental health days?",
  "Do you support the plan to require gig platforms to offer basic worker benefits?",
  "Do you support the plan to require influencers to disclose paid partnerships clearly?",
  "Do you support the plan to require landlords to meet a minimum energy-efficiency standard?",
  "Do you support the plan to require national service for young adults?",
  "Do you support the plan to require nutrition labels on restaurant menus?",
  "Do you support the plan to require paid parental leave for all new parents?",
  "Do you support the plan to require political ads to be fact-checked before airing?",
  "Do you support the plan to require restaurants to compost their food waste?",
  "Do you support the plan to require self-driving cars to pass a public safety audit?",
  "Do you support the plan to require social media platforms to verify user identity?",
  "Do you support the plan to require tech companies to open-source their algorithms?",
  "Do you support the plan to require warning labels on addictive app features?",
  "Do you support the plan to require warning labels on ultra-processed food?",
  "Do you support the plan to tax carbon emissions at the source?",
  "Is a four-day work week better than a five-day work week?",
  "Is automation better than human labor?",
  "Is cash better than digital currency?",
  "Is censorship better than free speech absolutism?",
  "Is city living better than rural living?",
  "Is competition better than collaboration?",
  "Is democracy better than technocracy?",
  "Is early rising better than night-owl schedules?",
  "Is electric cars better than public transit?",
  "Is free markets better than regulated markets?",
  "Is generalist careers better than specialist careers?",
  "Is globalization better than localism?",
  "Is hard skills better than soft skills?",
  "Is individual sports better than team sports?",
  "Is intuition better than data?",
  "Is it right to abolish credit scores as a hiring criterion?",
  "Is it right to abolish daylight billboard advertising in cities?",
  "Is it right to abolish daylight saving time?",
  "Is it right to abolish exclusivity deals between streaming platforms and studios?",
  "Is it right to abolish for-profit prisons?",
  "Is it right to abolish homework in schools?",
  "Is it right to abolish mandatory overtime in hospitals?",
  "Is it right to abolish non-compete clauses in employment contracts?",
  "Is it right to abolish standardized school uniforms?",
  "Is it right to abolish standardized university entrance exams?",
  "Is it right to abolish the electoral college?",
  "Is it right to abolish the penny and round all cash transactions?",
  "Is it right to abolish tipping and build service costs into prices?",
  "Is it right to abolish unpaid student teaching placements?",
  "Is it right to ban autonomous weapons in warfare?",
  "Is it right to ban breed-specific legislation for dogs?",
  "Is it right to ban cosmetic testing on animals worldwide?",
  "Is it right to ban fast fashion advertising?",
  "Is it right to ban late fees on public library books?",
  "Is it right to ban leaf blowers and other small gas engines?",
  "Is it right to ban leaf litter burning in residential areas?",
  "Is it right to ban lobbying by corporations?",
  "Is it right to ban microplastic-shedding synthetic fabrics?",
  "Is it right to ban misleading 'natural' labels on food?",
  "Is it right to ban plastic microbeads in cosmetics?",
  "Is it right to ban plastic packaging for produce?",
  "Is it right to ban single-use coffee pods?",
  "Is it right to ban single-use plastic bags in grocery stores?",
  "Is it right to ban single-use plastics nationwide?",
  "Is it right to ban social media for under-16s?",
  "Is it right to ban surge pricing during emergencies?",
  "Is it right to ban surge pricing on essential medicines?",
  "Is it right to ban targeted political ads on social media?",
  "Is it right to ban the sale of exotic animals as pets?",
  "Is it right to ban the use of child actors in advertising?",
  "Is it right to ban unpaid internships?",
  "Is it right to ban zoos and aquariums?",
  "Is it right to give animals basic legal rights?",
  "Is it right to give citizens a legal right to paid sick leave?",
  "Is it right to give citizens a say in how police budgets are spent?",
  "Is it right to give citizens free annual health checkups?",
  "Is it right to give citizens free legal aid for housing disputes?",
  "Is it right to give citizens paid time off to vote?",
  "Is it right to give citizens the right to a four-day school week?",
  "Is it right to give citizens the right to disconnect after work hours?",
  "Is it right to give citizens the right to vote at sixteen?",
  "Is it right to give employees a seat on every corporate board?",
  "Is it right to give every citizen a universal basic income?",
  "Is it right to give every citizen thirty days of paid leave a year?",
  "Is it right to give every student access to free school meals?",
  "Is it right to give every worker the right to a four-day trial workweek?",
  "Is it right to give farmers direct subsidies instead of market price supports?",
  "Is it right to give renters a legal cap on annual rent increases?",
  "Is it right to give renters the right to buy the home they rent?",
  "Is it right to give small businesses priority in public procurement?",
  "Is it right to give whistleblowers guaranteed legal protection?",
  "Is it right to grant legal personhood to advanced AI systems?",
  "Is it right to legalize all recreational drugs?",
  "Is it right to make climate education mandatory in schools?",
  "Is it right to make college tuition free at public universities?",
  "Is it right to make companies responsible for recycling their own products?",
  "Is it right to make every new appliance carry an energy-use label?",
  "Is it right to make financial literacy a required school subject?",
  "Is it right to make four-day work weeks the legal standard?",
  "Is it right to make it a legal right to work remotely where the job allows it?",
  "Is it right to make it illegal to fire someone without cause?",
  "Is it right to make it illegal to patent naturally occurring genes?",
  "Is it right to make it mandatory for airlines to compensate for long delays?",
  "Is it right to make it mandatory for landlords to allow pets?",
  "Is it right to make it mandatory to label lab-grown meat clearly?",
  "Is it right to make it mandatory to learn CPR in high school?",
  "Is it right to make jury duty compensated at a living wage?",
  "Is it right to make menstrual products free in public restrooms?",
  "Is it right to make organ donation opt-out by default?",
  "Is it right to make patents on life-saving drugs expire faster?",
  "Is it right to make public bathrooms free everywhere?",
  "Is it right to make public defenders as well-funded as prosecutors?",
  "Is it right to make public libraries offer free internet and device loans?",
  "Is it right to make public parks off-limits to pesticide use?",
  "Is it right to make public transit fare based on income?",
  "Is it right to make recycling contamination fines apply to households?",
  "Is it right to make space exploration a shared global effort rather than a national one?",
  "Is it right to make term limits mandatory for legislators?",
  "Is it right to make voter registration automatic at eighteen?",
  "Is it right to replace standardized testing with project-based assessment?",
  "Is it right to require all new buildings to be carbon neutral?",
  "Is it right to require all packaging to be compostable within five years?",
  "Is it right to require all schools to teach a second language from age five?",
  "Is it right to require banks to offer free basic accounts?",
  "Is it right to require companies to disclose their carbon footprint?",
  "Is it right to require companies to give workers equity instead of bonuses?",
  "Is it right to require companies to offer a living wage internship?",
  "Is it right to require companies to offer opt-out of algorithmic feeds?",
  "Is it right to require companies to take back their own packaging?",
  "Is it right to require companies to test AI systems for bias before release?",
  "Is it right to require every city bus to be wheelchair accessible?",
  "Is it right to require every city to have a minimum share of green space?",
  "Is it right to require every new car sold to be electric within a decade?",
  "Is it right to require every new mall to include public seating and shade?",
  "Is it right to require every new phone to have a replaceable battery?",
  "Is it right to require every school to grow its own vegetable garden?",
  "Is it right to require every workplace to offer mental health days?",
  "Is it right to require gig platforms to offer basic worker benefits?",
  "Is it right to require influencers to disclose paid partnerships clearly?",
  "Is it right to require landlords to meet a minimum energy-efficiency standard?",
  "Is it right to require political ads to be fact-checked before airing?",
  "Is it right to require restaurants to compost their food waste?",
  "Is it right to require self-driving cars to pass a public safety audit?",
  "Is it right to require warning labels on ultra-processed food?",
  "Is it right to tax carbon emissions at the source?",
  "Is it time to abolish credit scores as a hiring criterion?",
  "Is it time to abolish daylight billboard advertising in cities?",
  "Is it time to abolish daylight saving time?",
  "Is it time to abolish exclusivity deals between streaming platforms and studios?",
  "Is it time to abolish for-profit prisons?",
  "Is it time to abolish grades in favor of narrative feedback?",
  "Is it time to abolish homework in schools?",
  "Is it time to abolish legacy admissions at universities?",
  "Is it time to abolish mandatory overtime in hospitals?",
  "Is it time to abolish mandatory retirement ages?",
  "Is it time to abolish minimum order fees for food delivery?",
  "Is it time to abolish non-compete clauses in employment contracts?",
  "Is it time to abolish standardized dress codes at work?",
  "Is it time to abolish standardized school uniforms?",
  "Is it time to abolish standardized university entrance exams?",
  "Is it time to abolish the death penalty worldwide?",
  "Is it time to abolish the electoral college?",
  "Is it time to abolish the penny and round all cash transactions?",
  "Is it time to abolish tipping and build service costs into prices?",
  "Is it time to abolish unpaid overtime?",
  "Is it time to abolish unpaid student teaching placements?",
  "Is it time to ban advertising during children's television?",
  "Is it time to ban autonomous weapons in warfare?",
  "Is it time to ban breed-specific legislation for dogs?",
  "Is it time to ban cosmetic testing on animals worldwide?",
  "Is it time to ban drive-through lanes at new restaurants?",
  "Is it time to ban excessive packaging on online orders?",
  "Is it time to ban facial recognition in public spaces?",
  "Is it time to ban fast fashion advertising?",
  "Is it time to ban gas-powered cars in city centers?",
  "Is it time to ban late fees on public library books?",
  "Is it time to ban leaf blowers and other small gas engines?",
  "Is it time to ban leaf litter burning in residential areas?",
  "Is it time to ban lobbying by corporations?",
  "Is it time to ban microplastic-shedding synthetic fabrics?",
  "Is it time to ban misleading 'natural' labels on food?",
  "Is it time to ban planned obsolescence in consumer electronics?",
  "Is it time to ban plastic microbeads in cosmetics?",
  "Is it time to ban plastic packaging for produce?",
  "Is it time to ban plastic straws and cutlery in restaurants?",
  "Is it time to ban predatory payday lending?",
  "Is it time to ban predictive policing algorithms?",
  "Is it time to ban private ownership of handguns?",
  "Is it time to ban single-use coffee pods?",
  "Is it time to ban single-use plastic bags in grocery stores?",
  "Is it time to ban single-use plastics nationwide?",
  "Is it time to ban social media for under-16s?",
  "Is it time to ban surge pricing during emergencies?",
  "Is it time to ban surge pricing on essential medicines?",
  "Is it time to ban targeted advertising to children?",
  "Is it time to ban targeted political ads on social media?",
  "Is it time to ban the sale of energy drinks to minors?",
  "Is it time to ban the sale of exotic animals as pets?",
  "Is it time to ban the use of child actors in advertising?",
  "Is it time to ban unpaid internships?",
  "Is it time to ban unsolicited robocalls entirely?",
  "Is it time to ban zoos and aquariums?",
  "Is it time to cap CEO pay at a fixed multiple of the lowest-paid worker?",
  "Is it time to give animals basic legal rights?",
  "Is it time to give citizens a legal right to be forgotten online?",
  "Is it time to give citizens a legal right to paid sick leave?",
  "Is it time to give citizens a right to a paper ballot as backup?",
  "Is it time to give citizens a right to repair their own devices?",
  "Is it time to give citizens a right to request a human customer service agent?",
  "Is it time to give citizens a say in how police budgets are spent?",
  "Is it time to give citizens free annual health checkups?",
  "Is it time to give citizens free legal aid for housing disputes?",
  "Is it time to give citizens paid time off to vote?",
  "Is it time to give citizens the right to a four-day school week?",
  "Is it time to give citizens the right to disconnect after work hours?",
  "Is it time to give citizens the right to vote at sixteen?",
  "Is it time to give employees a seat on every corporate board?",
  "Is it time to give every citizen a universal basic income?",
  "Is it time to give every citizen thirty days of paid leave a year?",
  "Is it time to give every new parent a state-funded newborn care package?",
  "Is it time to give every student access to free school meals?",
  "Is it time to give every worker the right to a four-day trial workweek?",
  "Is it time to give farmers direct subsidies instead of market price supports?",
  "Is it time to give renters a legal cap on annual rent increases?",
  "Is it time to give renters the right to buy the home they rent?",
  "Is it time to give small businesses priority in public procurement?",
  "Is it time to give small farms priority access to public land?",
  "Is it time to give whistleblowers guaranteed legal protection?",
  "Is it time to grant legal personhood to advanced AI systems?",
  "Is it time to legalize all recreational drugs?",
  "Is it time to make climate education mandatory in schools?",
  "Is it time to make college tuition free at public universities?",
  "Is it time to make companies responsible for recycling their own products?",
  "Is it time to make composting mandatory in cities?",
  "Is it time to make every new appliance carry an energy-use label?",
  "Is it time to make financial literacy a required school subject?",
  "Is it time to make four-day work weeks the legal standard?",
  "Is it time to make internet access a basic human right?",
  "Is it time to make it a legal right to work remotely where the job allows it?",
  "Is it time to make it illegal to advertise diet products to teenagers?",
  "Is it time to make it illegal to fire someone without cause?",
  "Is it time to make it illegal to make employees check email after hours?",
  "Is it time to make it illegal to patent naturally occurring genes?",
  "Is it time to make it illegal to sell personal data without consent?",
  "Is it time to make it mandatory for airlines to compensate for long delays?",
  "Is it time to make it mandatory for hospitals to publish wait times?",
  "Is it time to make it mandatory for landlords to allow pets?",
  "Is it time to make it mandatory for schools to teach financial planning?",
  "Is it time to make it mandatory to label lab-grown meat clearly?",
  "Is it time to make it mandatory to learn CPR in high school?",
  "Is it time to make it mandatory to recycle electronics at point of sale?",
  "Is it time to make jury duty compensated at a living wage?",
  "Is it time to make menstrual products free in public restrooms?",
  "Is it time to make organ donation opt-out by default?",
  "Is it time to make patents on life-saving drugs expire faster?",
  "Is it time to make public bathrooms free everywhere?",
  "Is it time to make public defenders as well-funded as prosecutors?",
  "Is it time to make public libraries offer free internet and device loans?",
  "Is it time to make public parks off-limits to pesticide use?",
  "Is it time to make public transit fare based on income?",
  "Is it time to make public transport free for everyone?",
  "Is it time to make recycling contamination fines apply to households?",
  "Is it time to make space exploration a shared global effort rather than a national one?",
  "Is it time to make term limits mandatory for legislators?",
  "Is it time to make traffic fines proportional to income?",
  "Is it time to make voter registration automatic at eighteen?",
  "Is it time to make voting mandatory for all adults?",
  "Is it time to make voting possible entirely online?",
  "Is it time to replace prisons with rehabilitation-focused centers?",
  "Is it time to replace standardized testing with project-based assessment?",
  "Is it time to require a license to have children?",
  "Is it time to require all new buildings to be carbon neutral?",
  "Is it time to require all packaging to be compostable within five years?",
  "Is it time to require all schools to teach a second language from age five?",
  "Is it time to require banks to offer free basic accounts?",
  "Is it time to require companies to disclose their carbon footprint?",
  "Is it time to require companies to fund the retraining of laid-off workers?",
  "Is it time to require companies to give workers equity instead of bonuses?",
  "Is it time to require companies to offer a living wage internship?",
  "Is it time to require companies to offer opt-out of algorithmic feeds?",
  "Is it time to require companies to publish supply chain audits?",
  "Is it time to require companies to publish their gender pay gap?",
  "Is it time to require companies to reveal what data they collect on users?",
  "Is it time to require companies to take back their own packaging?",
  "Is it time to require companies to test AI systems for bias before release?",
  "Is it time to require ethics training for every engineer?",
  "Is it time to require every apartment building to have a compost bin?",
  "Is it time to require every citizen to vote or pay a fine?",
  "Is it time to require every city bus to be wheelchair accessible?",
  "Is it time to require every city to have a minimum share of green space?",
  "Is it time to require every new car sold to be electric within a decade?",
  "Is it time to require every new home to include solar panels?",
  "Is it time to require every new mall to include public seating and shade?",
  "Is it time to require every new phone to have a replaceable battery?",
  "Is it time to require every school to grow its own vegetable garden?",
  "Is it time to require every school to have a mental health counselor on site?",
  "Is it time to require every workplace to offer mental health days?",
  "Is it time to require gig platforms to offer basic worker benefits?",
  "Is it time to require influencers to disclose paid partnerships clearly?",
  "Is it time to require landlords to meet a minimum energy-efficiency standard?",
  "Is it time to require national service for young adults?",
  "Is it time to require nutrition labels on restaurant menus?",
  "Is it time to require paid parental leave for all new parents?",
  "Is it time to require political ads to be fact-checked before airing?",
  "Is it time to require restaurants to compost their food waste?",
  "Is it time to require self-driving cars to pass a public safety audit?",
  "Is it time to require social media platforms to verify user identity?",
  "Is it time to require tech companies to open-source their algorithms?",
  "Is it time to require warning labels on addictive app features?",
  "Is it time to require warning labels on ultra-processed food?",
  "Is it time to tax carbon emissions at the source?",
  "Is meritocracy better than equality of outcome?",
  "Is national identity better than global citizenship?",
  "Is nuclear energy better than renewable energy?",
  "Is online learning better than in-person learning?",
  "Is optimism better than realism?",
  "Is planned economies better than market economies?",
  "Is printed books better than e-books?",
  "Is public schools better than private schools?",
  "Is reading fiction better than reading nonfiction?",
  "Is remote work better than in-office work?",
  "Is short-term rentals better than long-term housing?",
  "Is single-parent households better than co-parenting arrangements?",
  "Is space exploration better than ocean exploration?",
  "Is subtitles better than dubbing?",
  "Is traditional classrooms better than self-directed learning?",
  "Should we abolish credit scores as a hiring criterion?",
  "Should we abolish daylight billboard advertising in cities?",
  "Should we abolish daylight saving time?",
  "Should we abolish exclusivity deals between streaming platforms and studios?",
  "Should we abolish for-profit prisons?",
  "Should we abolish grades in favor of narrative feedback?",
  "Should we abolish homework in schools?",
  "Should we abolish legacy admissions at universities?",
  "Should we abolish mandatory overtime in hospitals?",
  "Should we abolish mandatory retirement ages?",
  "Should we abolish minimum order fees for food delivery?",
  "Should we abolish non-compete clauses in employment contracts?",
  "Should we abolish standardized dress codes at work?",
  "Should we abolish standardized school uniforms?",
  "Should we abolish standardized university entrance exams?",
  "Should we abolish the death penalty worldwide?",
  "Should we abolish the electoral college?",
  "Should we abolish the penny and round all cash transactions?",
  "Should we abolish tipping and build service costs into prices?",
  "Should we abolish unpaid overtime?",
  "Should we abolish unpaid student teaching placements?",
  "Should we ban advertising during children's television?",
  "Should we ban autonomous weapons in warfare?",
  "Should we ban breed-specific legislation for dogs?",
  "Should we ban cosmetic testing on animals worldwide?",
  "Should we ban drive-through lanes at new restaurants?",
  "Should we ban excessive packaging on online orders?",
  "Should we ban facial recognition in public spaces?",
  "Should we ban fast fashion advertising?",
  "Should we ban gas-powered cars in city centers?",
  "Should we ban late fees on public library books?",
  "Should we ban leaf blowers and other small gas engines?",
  "Should we ban leaf litter burning in residential areas?",
  "Should we ban lobbying by corporations?",
  "Should we ban microplastic-shedding synthetic fabrics?",
  "Should we ban misleading 'natural' labels on food?",
  "Should we ban planned obsolescence in consumer electronics?",
  "Should we ban plastic microbeads in cosmetics?",
  "Should we ban plastic packaging for produce?",
  "Should we ban plastic straws and cutlery in restaurants?",
  "Should we ban predatory payday lending?",
  "Should we ban predictive policing algorithms?",
  "Should we ban private ownership of handguns?",
  "Should we ban single-use coffee pods?",
  "Should we ban single-use plastic bags in grocery stores?",
  "Should we ban single-use plastics nationwide?",
  "Should we ban social media for under-16s?",
  "Should we ban surge pricing during emergencies?",
  "Should we ban surge pricing on essential medicines?",
  "Should we ban targeted advertising to children?",
  "Should we ban targeted political ads on social media?",
  "Should we ban the sale of energy drinks to minors?",
  "Should we ban the sale of exotic animals as pets?",
  "Should we ban the use of child actors in advertising?",
  "Should we ban unpaid internships?",
  "Should we ban unsolicited robocalls entirely?",
  "Should we ban zoos and aquariums?",
  "Should we cap CEO pay at a fixed multiple of the lowest-paid worker?",
  "Should we give animals basic legal rights?",
  "Should we give citizens a legal right to be forgotten online?",
  "Should we give citizens a legal right to paid sick leave?",
  "Should we give citizens a right to a paper ballot as backup?",
  "Should we give citizens a right to repair their own devices?",
  "Should we give citizens a right to request a human customer service agent?",
  "Should we give citizens a say in how police budgets are spent?",
  "Should we give citizens free annual health checkups?",
  "Should we give citizens free legal aid for housing disputes?",
  "Should we give citizens paid time off to vote?",
  "Should we give citizens the right to a four-day school week?",
  "Should we give citizens the right to disconnect after work hours?",
  "Should we give citizens the right to vote at sixteen?",
  "Should we give employees a seat on every corporate board?",
  "Should we give every citizen a universal basic income?",
  "Should we give every citizen thirty days of paid leave a year?",
  "Should we give every new parent a state-funded newborn care package?",
  "Should we give every student access to free school meals?",
  "Should we give every worker the right to a four-day trial workweek?",
  "Should we give farmers direct subsidies instead of market price supports?",
  "Should we give renters a legal cap on annual rent increases?",
  "Should we give renters the right to buy the home they rent?",
  "Should we give small businesses priority in public procurement?",
  "Should we give small farms priority access to public land?",
  "Should we give whistleblowers guaranteed legal protection?",
  "Should we grant legal personhood to advanced AI systems?",
  "Should we legalize all recreational drugs?",
  "Should we make climate education mandatory in schools?",
  "Should we make college tuition free at public universities?",
  "Should we make companies responsible for recycling their own products?",
  "Should we make composting mandatory in cities?",
  "Should we make every new appliance carry an energy-use label?",
  "Should we make financial literacy a required school subject?",
  "Should we make four-day work weeks the legal standard?",
  "Should we make internet access a basic human right?",
  "Should we make it a legal right to work remotely where the job allows it?",
  "Should we make it illegal to advertise diet products to teenagers?",
  "Should we make it illegal to fire someone without cause?",
  "Should we make it illegal to make employees check email after hours?",
  "Should we make it illegal to patent naturally occurring genes?",
  "Should we make it illegal to sell personal data without consent?",
  "Should we make it mandatory for airlines to compensate for long delays?",
  "Should we make it mandatory for hospitals to publish wait times?",
  "Should we make it mandatory for landlords to allow pets?",
  "Should we make it mandatory for schools to teach financial planning?",
  "Should we make it mandatory to label lab-grown meat clearly?",
  "Should we make it mandatory to learn CPR in high school?",
  "Should we make it mandatory to recycle electronics at point of sale?",
  "Should we make jury duty compensated at a living wage?",
  "Should we make menstrual products free in public restrooms?",
  "Should we make organ donation opt-out by default?",
  "Should we make patents on life-saving drugs expire faster?",
  "Should we make public bathrooms free everywhere?",
  "Should we make public defenders as well-funded as prosecutors?",
  "Should we make public libraries offer free internet and device loans?",
  "Should we make public parks off-limits to pesticide use?",
  "Should we make public transit fare based on income?",
  "Should we make public transport free for everyone?",
  "Should we make recycling contamination fines apply to households?",
  "Should we make space exploration a shared global effort rather than a national one?",
  "Should we make term limits mandatory for legislators?",
  "Should we make traffic fines proportional to income?",
  "Should we make voter registration automatic at eighteen?",
  "Should we make voting mandatory for all adults?",
  "Should we make voting possible entirely online?",
  "Should we replace prisons with rehabilitation-focused centers?",
  "Should we replace standardized testing with project-based assessment?",
  "Should we require a license to have children?",
  "Should we require all new buildings to be carbon neutral?",
  "Should we require all packaging to be compostable within five years?",
  "Should we require all schools to teach a second language from age five?",
  "Should we require banks to offer free basic accounts?",
  "Should we require companies to disclose their carbon footprint?",
  "Should we require companies to fund the retraining of laid-off workers?",
  "Should we require companies to give workers equity instead of bonuses?",
  "Should we require companies to offer a living wage internship?",
  "Should we require companies to offer opt-out of algorithmic feeds?",
  "Should we require companies to publish supply chain audits?",
  "Should we require companies to publish their gender pay gap?",
  "Should we require companies to reveal what data they collect on users?",
  "Should we require companies to take back their own packaging?",
  "Should we require companies to test AI systems for bias before release?",
  "Should we require ethics training for every engineer?",
  "Should we require every apartment building to have a compost bin?",
  "Should we require every citizen to vote or pay a fine?",
  "Should we require every city bus to be wheelchair accessible?",
  "Should we require every city to have a minimum share of green space?",
  "Should we require every new car sold to be electric within a decade?",
  "Should we require every new home to include solar panels?",
  "Should we require every new mall to include public seating and shade?",
  "Should we require every new phone to have a replaceable battery?",
  "Should we require every school to grow its own vegetable garden?",
  "Should we require every school to have a mental health counselor on site?",
  "Should we require every workplace to offer mental health days?",
  "Should we require gig platforms to offer basic worker benefits?",
  "Should we require influencers to disclose paid partnerships clearly?",
  "Should we require landlords to meet a minimum energy-efficiency standard?",
  "Should we require national service for young adults?",
  "Should we require nutrition labels on restaurant menus?",
  "Should we require paid parental leave for all new parents?",
  "Should we require political ads to be fact-checked before airing?",
  "Should we require restaurants to compost their food waste?",
  "Should we require self-driving cars to pass a public safety audit?",
  "Should we require social media platforms to verify user identity?",
  "Should we require tech companies to open-source their algorithms?",
  "Should we require warning labels on addictive app features?",
  "Should we require warning labels on ultra-processed food?",
  "Should we tax carbon emissions at the source?",
  "This house believes we should abolish credit scores as a hiring criterion.",
  "This house believes we should abolish daylight billboard advertising in cities.",
  "This house believes we should abolish daylight saving time.",
  "This house believes we should abolish exclusivity deals between streaming platforms and studios.",
  "This house believes we should abolish for-profit prisons.",
  "This house believes we should abolish grades in favor of narrative feedback.",
  "This house believes we should abolish homework in schools.",
  "This house believes we should abolish legacy admissions at universities.",
  "This house believes we should abolish mandatory overtime in hospitals.",
  "This house believes we should abolish mandatory retirement ages.",
  "This house believes we should abolish minimum order fees for food delivery.",
  "This house believes we should abolish non-compete clauses in employment contracts.",
  "This house believes we should abolish standardized dress codes at work.",
  "This house believes we should abolish standardized school uniforms.",
  "This house believes we should abolish standardized university entrance exams.",
  "This house believes we should abolish the death penalty worldwide.",
  "This house believes we should abolish the electoral college.",
  "This house believes we should abolish the penny and round all cash transactions.",
  "This house believes we should abolish tipping and build service costs into prices.",
  "This house believes we should abolish unpaid overtime.",
  "This house believes we should abolish unpaid student teaching placements.",
  "This house believes we should ban advertising during children's television.",
  "This house believes we should ban autonomous weapons in warfare.",
  "This house believes we should ban breed-specific legislation for dogs.",
  "This house believes we should ban cosmetic testing on animals worldwide.",
  "This house believes we should ban drive-through lanes at new restaurants.",
  "This house believes we should ban excessive packaging on online orders.",
  "This house believes we should ban facial recognition in public spaces.",
  "This house believes we should ban fast fashion advertising.",
  "This house believes we should ban gas-powered cars in city centers.",
  "This house believes we should ban late fees on public library books.",
  "This house believes we should ban leaf blowers and other small gas engines.",
  "This house believes we should ban leaf litter burning in residential areas.",
  "This house believes we should ban lobbying by corporations.",
  "This house believes we should ban microplastic-shedding synthetic fabrics.",
  "This house believes we should ban misleading 'natural' labels on food.",
  "This house believes we should ban planned obsolescence in consumer electronics.",
  "This house believes we should ban plastic microbeads in cosmetics.",
  "This house believes we should ban plastic packaging for produce.",
  "This house believes we should ban plastic straws and cutlery in restaurants.",
  "This house believes we should ban predatory payday lending.",
  "This house believes we should ban predictive policing algorithms.",
  "This house believes we should ban private ownership of handguns.",
  "This house believes we should ban single-use coffee pods.",
  "This house believes we should ban single-use plastic bags in grocery stores.",
  "This house believes we should ban single-use plastics nationwide.",
  "This house believes we should ban social media for under-16s.",
  "This house believes we should ban surge pricing during emergencies.",
  "This house believes we should ban surge pricing on essential medicines.",
  "This house believes we should ban targeted advertising to children.",
  "This house believes we should ban targeted political ads on social media.",
  "This house believes we should ban the sale of energy drinks to minors.",
  "This house believes we should ban the sale of exotic animals as pets.",
  "This house believes we should ban the use of child actors in advertising.",
  "This house believes we should ban unpaid internships.",
  "This house believes we should ban unsolicited robocalls entirely.",
  "This house believes we should ban zoos and aquariums.",
  "This house believes we should cap CEO pay at a fixed multiple of the lowest-paid worker.",
  "This house believes we should give animals basic legal rights.",
  "This house believes we should give citizens a legal right to be forgotten online.",
  "This house believes we should give citizens a legal right to paid sick leave.",
  "This house believes we should give citizens a right to a paper ballot as backup.",
  "This house believes we should give citizens a right to repair their own devices.",
  "This house believes we should give citizens a right to request a human customer service agent.",
  "This house believes we should give citizens a say in how police budgets are spent.",
  "This house believes we should give citizens free annual health checkups.",
  "This house believes we should give citizens free legal aid for housing disputes.",
  "This house believes we should give citizens paid time off to vote.",
  "This house believes we should give citizens the right to a four-day school week.",
  "This house believes we should give citizens the right to disconnect after work hours.",
  "This house believes we should give citizens the right to vote at sixteen.",
  "This house believes we should give employees a seat on every corporate board.",
  "This house believes we should give every citizen a universal basic income.",
  "This house believes we should give every citizen thirty days of paid leave a year.",
  "This house believes we should give every new parent a state-funded newborn care package.",
  "This house believes we should give every student access to free school meals.",
  "This house believes we should give every worker the right to a four-day trial workweek.",
  "This house believes we should give farmers direct subsidies instead of market price supports.",
  "This house believes we should give renters a legal cap on annual rent increases.",
  "This house believes we should give renters the right to buy the home they rent.",
  "This house believes we should give small businesses priority in public procurement.",
  "This house believes we should give small farms priority access to public land.",
  "This house believes we should give whistleblowers guaranteed legal protection.",
  "This house believes we should grant legal personhood to advanced AI systems.",
  "This house believes we should legalize all recreational drugs.",
  "This house believes we should make climate education mandatory in schools.",
  "This house believes we should make college tuition free at public universities.",
  "This house believes we should make companies responsible for recycling their own products.",
  "This house believes we should make composting mandatory in cities.",
  "This house believes we should make every new appliance carry an energy-use label.",
  "This house believes we should make financial literacy a required school subject.",
  "This house believes we should make four-day work weeks the legal standard.",
  "This house believes we should make internet access a basic human right.",
  "This house believes we should make it a legal right to work remotely where the job allows it.",
  "This house believes we should make it illegal to advertise diet products to teenagers.",
  "This house believes we should make it illegal to fire someone without cause.",
  "This house believes we should make it illegal to make employees check email after hours.",
  "This house believes we should make it illegal to patent naturally occurring genes.",
  "This house believes we should make it illegal to sell personal data without consent.",
  "This house believes we should make it mandatory for airlines to compensate for long delays.",
  "This house believes we should make it mandatory for hospitals to publish wait times.",
  "This house believes we should make it mandatory for landlords to allow pets.",
  "This house believes we should make it mandatory for schools to teach financial planning.",
  "This house believes we should make it mandatory to label lab-grown meat clearly.",
  "This house believes we should make it mandatory to learn CPR in high school.",
  "This house believes we should make it mandatory to recycle electronics at point of sale.",
  "This house believes we should make jury duty compensated at a living wage.",
  "This house believes we should make menstrual products free in public restrooms.",
  "This house believes we should make organ donation opt-out by default.",
  "This house believes we should make patents on life-saving drugs expire faster.",
  "This house believes we should make public bathrooms free everywhere.",
  "This house believes we should make public defenders as well-funded as prosecutors.",
  "This house believes we should make public libraries offer free internet and device loans.",
  "This house believes we should make public parks off-limits to pesticide use.",
  "This house believes we should make public transit fare based on income.",
  "This house believes we should make public transport free for everyone.",
  "This house believes we should make recycling contamination fines apply to households.",
  "This house believes we should make space exploration a shared global effort rather than a national one.",
  "This house believes we should make term limits mandatory for legislators.",
  "This house believes we should make traffic fines proportional to income.",
  "This house believes we should make voter registration automatic at eighteen.",
  "This house believes we should make voting mandatory for all adults.",
  "This house believes we should make voting possible entirely online.",
  "This house believes we should replace prisons with rehabilitation-focused centers.",
  "This house believes we should replace standardized testing with project-based assessment.",
  "This house believes we should require a license to have children.",
  "This house believes we should require all new buildings to be carbon neutral.",
  "This house believes we should require all packaging to be compostable within five years.",
  "This house believes we should require all schools to teach a second language from age five.",
  "This house believes we should require banks to offer free basic accounts.",
  "This house believes we should require companies to disclose their carbon footprint.",
  "This house believes we should require companies to fund the retraining of laid-off workers.",
  "This house believes we should require companies to give workers equity instead of bonuses.",
  "This house believes we should require companies to offer a living wage internship.",
  "This house believes we should require companies to offer opt-out of algorithmic feeds.",
  "This house believes we should require companies to publish supply chain audits.",
  "This house believes we should require companies to publish their gender pay gap.",
  "This house believes we should require companies to reveal what data they collect on users.",
  "This house believes we should require companies to take back their own packaging.",
  "This house believes we should require companies to test AI systems for bias before release.",
  "This house believes we should require ethics training for every engineer.",
  "This house believes we should require every apartment building to have a compost bin.",
  "This house believes we should require every citizen to vote or pay a fine.",
  "This house believes we should require every city bus to be wheelchair accessible.",
  "This house believes we should require every city to have a minimum share of green space.",
  "This house believes we should require every new car sold to be electric within a decade.",
  "This house believes we should require every new home to include solar panels.",
  "This house believes we should require every new mall to include public seating and shade.",
  "This house believes we should require every new phone to have a replaceable battery.",
  "This house believes we should require every school to grow its own vegetable garden.",
  "This house believes we should require every school to have a mental health counselor on site.",
  "This house believes we should require every workplace to offer mental health days.",
  "This house believes we should require gig platforms to offer basic worker benefits.",
  "This house believes we should require influencers to disclose paid partnerships clearly.",
  "This house believes we should require landlords to meet a minimum energy-efficiency standard.",
  "This house believes we should require national service for young adults.",
  "This house believes we should require nutrition labels on restaurant menus.",
  "This house believes we should require paid parental leave for all new parents.",
  "This house believes we should require political ads to be fact-checked before airing.",
  "This house believes we should require restaurants to compost their food waste.",
  "This house believes we should require self-driving cars to pass a public safety audit.",
  "This house believes we should require social media platforms to verify user identity.",
  "This house believes we should require tech companies to open-source their algorithms.",
  "This house believes we should require warning labels on addictive app features.",
  "This house believes we should require warning labels on ultra-processed food.",
  "This house believes we should tax carbon emissions at the source.",
  "This house prefers a four-day work week to a five-day work week.",
  "This house prefers automation to human labor.",
  "This house prefers cash to digital currency.",
  "This house prefers censorship to free speech absolutism.",
  "This house prefers city living to rural living.",
  "This house prefers competition to collaboration.",
  "This house prefers democracy to technocracy.",
  "This house prefers early rising to night-owl schedules.",
  "This house prefers electric cars to public transit.",
  "This house prefers free markets to regulated markets.",
  "This house prefers generalist careers to specialist careers.",
  "This house prefers globalization to localism.",
  "This house prefers hard skills to soft skills.",
  "This house prefers individual sports to team sports.",
  "This house prefers intuition to data.",
  "This house prefers meritocracy to equality of outcome.",
  "This house prefers national identity to global citizenship.",
  "This house prefers nuclear energy to renewable energy.",
  "This house prefers online learning to in-person learning.",
  "This house prefers optimism to realism.",
  "This house prefers planned economies to market economies.",
  "This house prefers printed books to e-books.",
  "This house prefers public schools to private schools.",
  "This house prefers reading fiction to reading nonfiction.",
  "This house prefers remote work to in-office work.",
  "This house prefers short-term rentals to long-term housing.",
  "This house prefers single-parent households to co-parenting arrangements.",
  "This house prefers space exploration to ocean exploration.",
  "This house prefers subtitles to dubbing.",
  "This house prefers traditional classrooms to self-directed learning.",
  "This house would abolish credit scores as a hiring criterion.",
  "This house would abolish daylight billboard advertising in cities.",
  "This house would abolish daylight saving time.",
  "This house would abolish exclusivity deals between streaming platforms and studios.",
  "This house would abolish for-profit prisons.",
  "This house would abolish grades in favor of narrative feedback.",
  "This house would abolish homework in schools.",
  "This house would abolish legacy admissions at universities.",
  "This house would abolish mandatory overtime in hospitals.",
  "This house would abolish mandatory retirement ages.",
  "This house would abolish minimum order fees for food delivery.",
  "This house would abolish non-compete clauses in employment contracts.",
  "This house would abolish standardized dress codes at work.",
  "This house would abolish standardized school uniforms.",
  "This house would abolish standardized university entrance exams.",
  "This house would abolish the death penalty worldwide.",
  "This house would abolish the electoral college.",
  "This house would abolish the penny and round all cash transactions.",
  "This house would abolish tipping and build service costs into prices.",
  "This house would abolish unpaid overtime.",
  "This house would abolish unpaid student teaching placements.",
  "This house would ban advertising during children's television.",
  "This house would ban autonomous weapons in warfare.",
  "This house would ban breed-specific legislation for dogs.",
  "This house would ban cosmetic testing on animals worldwide.",
  "This house would ban drive-through lanes at new restaurants.",
  "This house would ban excessive packaging on online orders.",
  "This house would ban facial recognition in public spaces.",
  "This house would ban fast fashion advertising.",
  "This house would ban gas-powered cars in city centers.",
  "This house would ban late fees on public library books.",
  "This house would ban leaf blowers and other small gas engines.",
  "This house would ban leaf litter burning in residential areas.",
  "This house would ban lobbying by corporations.",
  "This house would ban microplastic-shedding synthetic fabrics.",
  "This house would ban misleading 'natural' labels on food.",
  "This house would ban planned obsolescence in consumer electronics.",
  "This house would ban plastic microbeads in cosmetics.",
  "This house would ban plastic packaging for produce.",
  "This house would ban plastic straws and cutlery in restaurants.",
  "This house would ban predatory payday lending.",
  "This house would ban predictive policing algorithms.",
  "This house would ban private ownership of handguns.",
  "This house would ban single-use coffee pods.",
  "This house would ban single-use plastic bags in grocery stores.",
  "This house would ban single-use plastics nationwide.",
  "This house would ban social media for under-16s.",
  "This house would ban surge pricing during emergencies.",
  "This house would ban surge pricing on essential medicines.",
  "This house would ban targeted advertising to children.",
  "This house would ban targeted political ads on social media.",
  "This house would ban the sale of energy drinks to minors.",
  "This house would ban the sale of exotic animals as pets.",
  "This house would ban the use of child actors in advertising.",
  "This house would ban unpaid internships.",
  "This house would ban unsolicited robocalls entirely.",
  "This house would ban zoos and aquariums.",
  "This house would cap CEO pay at a fixed multiple of the lowest-paid worker.",
  "This house would give animals basic legal rights.",
  "This house would give citizens a legal right to be forgotten online.",
  "This house would give citizens a legal right to paid sick leave.",
  "This house would give citizens a right to a paper ballot as backup.",
  "This house would give citizens a right to repair their own devices.",
  "This house would give citizens a right to request a human customer service agent.",
  "This house would give citizens a say in how police budgets are spent.",
  "This house would give citizens free annual health checkups.",
  "This house would give citizens free legal aid for housing disputes.",
  "This house would give citizens paid time off to vote.",
  "This house would give citizens the right to a four-day school week.",
  "This house would give citizens the right to disconnect after work hours.",
  "This house would give citizens the right to vote at sixteen.",
  "This house would give employees a seat on every corporate board.",
  "This house would give every citizen a universal basic income.",
  "This house would give every citizen thirty days of paid leave a year.",
  "This house would give every new parent a state-funded newborn care package.",
  "This house would give every student access to free school meals.",
  "This house would give every worker the right to a four-day trial workweek.",
  "This house would give farmers direct subsidies instead of market price supports.",
  "This house would give renters a legal cap on annual rent increases.",
  "This house would give renters the right to buy the home they rent.",
  "This house would give small businesses priority in public procurement.",
  "This house would give small farms priority access to public land.",
  "This house would give whistleblowers guaranteed legal protection.",
  "This house would grant legal personhood to advanced AI systems.",
  "This house would legalize all recreational drugs.",
  "This house would make climate education mandatory in schools.",
  "This house would make college tuition free at public universities.",
  "This house would make companies responsible for recycling their own products.",
  "This house would make composting mandatory in cities.",
  "This house would make every new appliance carry an energy-use label.",
  "This house would make financial literacy a required school subject.",
  "This house would make four-day work weeks the legal standard.",
  "This house would make internet access a basic human right.",
  "This house would make it a legal right to work remotely where the job allows it.",
  "This house would make it illegal to advertise diet products to teenagers.",
  "This house would make it illegal to fire someone without cause.",
  "This house would make it illegal to make employees check email after hours.",
  "This house would make it illegal to patent naturally occurring genes.",
  "This house would make it illegal to sell personal data without consent.",
  "This house would make it mandatory for airlines to compensate for long delays.",
  "This house would make it mandatory for hospitals to publish wait times.",
  "This house would make it mandatory for landlords to allow pets.",
  "This house would make it mandatory for schools to teach financial planning.",
  "This house would make it mandatory to label lab-grown meat clearly.",
  "This house would make it mandatory to learn CPR in high school.",
  "This house would make it mandatory to recycle electronics at point of sale.",
  "This house would make jury duty compensated at a living wage.",
  "This house would make menstrual products free in public restrooms.",
  "This house would make organ donation opt-out by default.",
  "This house would make patents on life-saving drugs expire faster.",
  "This house would make public bathrooms free everywhere.",
  "This house would make public defenders as well-funded as prosecutors.",
  "This house would make public libraries offer free internet and device loans.",
  "This house would make public parks off-limits to pesticide use.",
  "This house would make public transit fare based on income.",
  "This house would make public transport free for everyone.",
  "This house would make recycling contamination fines apply to households.",
  "This house would make space exploration a shared global effort rather than a national one.",
  "This house would make term limits mandatory for legislators.",
  "This house would make traffic fines proportional to income.",
  "This house would make voter registration automatic at eighteen.",
  "This house would make voting mandatory for all adults.",
  "This house would make voting possible entirely online.",
  "This house would replace prisons with rehabilitation-focused centers.",
  "This house would replace standardized testing with project-based assessment.",
  "This house would require a license to have children.",
  "This house would require all new buildings to be carbon neutral.",
  "This house would require all packaging to be compostable within five years.",
  "This house would require all schools to teach a second language from age five.",
  "This house would require banks to offer free basic accounts.",
  "This house would require companies to disclose their carbon footprint.",
  "This house would require companies to fund the retraining of laid-off workers.",
  "This house would require companies to give workers equity instead of bonuses.",
  "This house would require companies to offer a living wage internship.",
  "This house would require companies to offer opt-out of algorithmic feeds.",
  "This house would require companies to publish supply chain audits.",
  "This house would require companies to publish their gender pay gap.",
  "This house would require companies to reveal what data they collect on users.",
  "This house would require companies to take back their own packaging.",
  "This house would require companies to test AI systems for bias before release.",
  "This house would require ethics training for every engineer.",
  "This house would require every apartment building to have a compost bin.",
  "This house would require every citizen to vote or pay a fine.",
  "This house would require every city bus to be wheelchair accessible.",
  "This house would require every city to have a minimum share of green space.",
  "This house would require every new car sold to be electric within a decade.",
  "This house would require every new home to include solar panels.",
  "This house would require every new mall to include public seating and shade.",
  "This house would require every new phone to have a replaceable battery.",
  "This house would require every school to grow its own vegetable garden.",
  "This house would require every school to have a mental health counselor on site.",
  "This house would require every workplace to offer mental health days.",
  "This house would require gig platforms to offer basic worker benefits.",
  "This house would require influencers to disclose paid partnerships clearly.",
  "This house would require landlords to meet a minimum energy-efficiency standard.",
  "This house would require national service for young adults.",
  "This house would require nutrition labels on restaurant menus.",
  "This house would require paid parental leave for all new parents.",
  "This house would require political ads to be fact-checked before airing.",
  "This house would require restaurants to compost their food waste.",
  "This house would require self-driving cars to pass a public safety audit.",
  "This house would require social media platforms to verify user identity.",
  "This house would require tech companies to open-source their algorithms.",
  "This house would require warning labels on addictive app features.",
  "This house would require warning labels on ultra-processed food.",
  "This house would tax carbon emissions at the source.",
];
